### ISSUE TITLE
Use JSON format to generate logs

### ISSUE THREAD

**Issue by luarx** [safe-global/safe-events-service#217]
It could be useful to use JSON instead of strings to generate logs.

The main reason are:
- Every new EVENT_TYPE has to be parsed in the monitoring system as each of them has different keys.
Using JSON, **every new key will be parsed automatically** 🚀 
- Every new log message has to be parsed

Currently, [safe-client-gateway](https://github.com/safe-global?q=client&type=all&language=&sort=) is using JSON format for logs, so it could be a good reference in case that this issue is implemented.

Example:
- Current log:
```
{
"timestamp":"2024-04-24T10:26:16.457Z",
"context":"WebhookService",
"level":"debug",
"message":"Success sending event {\"address\":\"0xc598397Ce2B8BDF93071c0446D1eEDC2141f01D0\",\"type\":\"NEW_CONFIRMATION\",\"owner\":\"0xD32FF562967d7174bf3608ff7bcd9c20956C813F\",\"safeTxHash\":\"0xc49e0646c7341bdd38553700014852360902771002f8bcfc9b13bf2c8467db74\",\"chainId\":\"100\"} to https://api.nestwallet.app/webhook/safe/event: 200 - \"\" [startTime: 1713954376299, endTime: 1713954376457, responseTime: 158ms]"
}
```
- Proposal:
```
{
"timestamp":"2024-04-24T10:26:16.457Z",
"context":"WebhookService",
"level":"debug",
"message": "Success sending event", 
"start_time": "1713954376299",
"end_time": "1713954376457", 
"response_time": "158ms", 
"status_code": "200", 
"route": "https://api.nestwallet.app/webhook/safe/event", 
"event_data": {"address": "0xc598397Ce2B8BDF93071c0446D1eEDC2141f01D0", " type ": "NEW_CONFIRMATION", "owner":"0xD32FF562967d7174bf3608ff7bcd9c20956C813F","safeTxHash":"0xc49e0646c7341bdd38553700014852360902771002f8bcfc9b13bf2c8467db74","chainId":"100"} 
}
```

Suggestions: 
- **snake_case** format would be more recommended
great power comes great responsibility
- Suggested property names in case that someone works:
```
{
  chain_id: string | null;
  client_ip: string | null;
  method: string;
  response_time_ms: number;
  route: string;
  path: string;
  status_code: number;
  detail: string | null;
  message: unknown;
  build_number: string | undefined;
  request_id: string;
  timestamp: string;
  version: string | undefined;
}
```

**Comment by moisses89** [comment]
@luarx just to confirm, would be possible filter later in the logs by `address` field for example? Maybe `event_data.address`?

**Comment by diegopazosrego** [comment]
No @moisses89 ! in this case we would map event_data.address to be address and the search would be done by @address as up to now

**Comment by Uxio0** [comment]
> snake_case format would be more recommended

@luarx I would prefer to use camelCase, as everything in a Typescript project, snake_case will make our linter complain and will look odd, what do you think?

**Comment by luarx** [comment]
Yes, no problem! It was a general recommendation but not a blocker 🙌

**Comment by Uxio0** [comment]
This is an example of the new structure, DYTK?

```json
 message: "Success sending event",
          event: parsedMessage,
          httpRequest: {
            url: url,
            startTime: startTime,
            endTime: endTime,
          },
          httpResponse: {
            data: responseData,
            statusCode: response.status,
            elapsedTimeMs: elapsedTime,
          },
```

**Comment by luarx** [comment]
Looks good to me 👍
